name: dumi webbook

on:
  push:
    branches:
      - main # default branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 下载node，我这里指定了15.x，这个版本可随意，高于dumi规定的node版本即可
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Build Project
        run: |
          npm install
          npm run build
        uses: actions/cache@v1
      # 文档编译命令，如果是 react 模板需要修改为 npm run docs:build
#        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages
#          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 文档目录，如果是 react 模板需要修改为 docs-dist
          publish_dir: ./dist
          folder: dist
